default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["BACK_DATABASE_HOST"] %>
  username: <%= ENV["BACK_DATABASE_USERNAME"] %>
  password: <%= ENV["BACK_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: back_development

test:
  <<: *default
  database: back_test

production:
  <<: *default
  database: back_production
